package com.zq.sword.array.redis.rdb.config;

public enum RedisValueType {

    REDIS_RDB_TYPE_STRING,
    REDIS_RDB_TYPE_LIST,
    REDIS_RDB_TYPE_SET,
    REDIS_RDB_TYPE_ZSET,
    REDIS_RDB_TYPE_HASH,
    REDIS_RDB_TYPE_LIST_ZIPLIST,
    REDIS_RDB_TYPE_SET_INTSET,
    REDIS_RDB_TYPE_ZSIT_ZIPLIST,
    REDIS_RDB_TYPE_HASH_ZIPLIST,
    ;
}
